### ISSUE TITLE
Make a script that converts a filesystem into a disk image

### ISSUE THREAD

**Issue by rhit-seilerar** [rhit-seilerar/exert-capstone#11]
The disk image can just be a raw format instead of qcow2.
Also, make the plugin use it instead of a generic qcow2.

Following XP principles, make a test before writing this.
 - Single test.py that tests everything else?
 - The test will run the converter and verify that a raw image is produced and that panda can run it

**Comment by rhit-frantzag** [comment]
Evan and I (Aidan Frantz) worked on it for about 30 minutes before running into an issue in which we needed advisor feedback.

**Comment by rhit-frantzag** [comment]
After further clarification from the client, the file can be a cpio image, and then use generic images for the qcow stuff. I'm right now researching how to load a RAM disk directly into Linux.

**Comment by rhit-frantzag** [comment]
Evan and I have figured out how to make a cpio file from a directory, but are having a lot of trouble figuring out how to get the Qemu system started using the cpio file that we created, so the test we initially wrote was broken. We'll need to continue working on this ticket, currently, we have put a total of 4 pair-hours into it.

**Comment by rhit-frantzag** [comment]
Evan and I have further figured out the stuff that needs to be on the initial filesystem to get Linux to boot, but we are still having trouble generating an initrd image from scratch that boots without errors. Unfortunately, qemu gives very unintuitive and often incorrect error messages for this problem, so further development is required. We've currently put a total of 6 pair-hours into it.

**Comment by rhit-frantzag** [comment]
Technically finished. The make_initrd.sh script, when run locally on a host machine, will generate a ramdisk that PANDA can boot without erroring. There will need to be improvements made to the integration of the script in Python, improvements to how the script runs in the Docker container, and to the ability to run serial commands in the container with the ramdisk, but this ticket is already way over time and the integration testing passes with the current very crude method.

Testing:
- Run sudo make_initrd.sh on a Linux machine to generate a ramdisk
- Uncomment the lines in plugin.py that run the file
- Comment out the generic Panda line and the line for running the uname serial command, as well as the hook
- Run plugin.py in Python in the Docker container.
- Snapshots will error, but otherwise the container will open and close as expected.
